language: csharp

sudo: false  # use the new container-based Travis infrastructure

before_install:
  - chmod +x build.sh

before_script:
 # Start a virtual framebuffer as described: https://docs.travis-ci.com/user/gui-and-headless-browsers/
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start

script:
  - travis_wait ./build.sh NuGet
  - mono .paket/paket.exe install
  - git diff --exit-code

after_script:
  - mono --debug --profile=log:coverage,covfilter=+OpenTK,covfilter=-OpenTK.Tests,covfilter=-FSharp.Core,covfilter=-FsCheck,covfilter=-xunit.assert "packages/xunit.runner.console/tools/xunit.console.exe"  "tests/OpenTK.Tests/bin/Release/OpenTK.Tests.dll" -parallel none
  - mprof-report --reports=coverage --coverage-out=coverage.xml output.mlpd
  - bash <(curl -s https://codecov.io/bash)
